import { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import './globals.css'

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
            <SignedIn>
          <header className="flex justify-end items-center p-4 gap-4 h-16">
              <UserButton />
          </header>
            </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )

}